apiVersion: v1
kind: Service
metadata:
  name: liferay-node-service
spec:
  type: NodePort
  selector:
    app: liferay
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: liferay
  name: liferay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liferay
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: liferay
    spec:
      volumes:
        - name: liferay-doclib-storage
          persistentVolumeClaim:
            claimName: liferay-docklib-pvc
      containers:
        - env:
            - name: LIFERAY_JAVA_OPTS
              value: -Xms2g -Xmx2g
            - name: LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE
              value: 0.0.0.0:11311
            - name: LIFERAY_WEB_PERIOD_SERVER_PERIOD_DISPLAY_PERIOD_NODE
              value: "true"
            - name: LIFERAY_REDIRECT_PERIOD_URL_PERIOD_SECURITY_PERIOD_MODE
              value: "domain"
          image: rkrishna79/liferay-dxp:7.2.10-sp5-BUILD_NO
          name: liferay
          ports:
            - containerPort: 11311
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: "/c/portal/layout"
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 15
            failureThreshold: 3
            successThreshold: 3
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 20
            failureThreshold: 3
            successThreshold: 1
          volumeMounts:
            - name: liferay-doclib-storage
              mountPath: /opt/liferay/data/document_library
              subPath: document_library
